### ISSUE TITLE
这个主题如何增加标签、分类这些功能？Tags, categories, etc.

### ISSUE THREAD

**Issue by liwh1227** [hanwenguo/hugo-theme-nostyleplease#14]
如题，我想基于这个主题增加标签、分类等功能，但是发现无法配置

As the title suggests, I want to add features such as tags and categories based on this theme, but I found that it cannot be configured.

**Comment by Masellum** [comment]
访问 `/tags/` 或者 `/categories/` 这两个路径即可打开对应汇总页面。如果想显示在主页上，配置 `menu.toml` 即可。

To open the corresponding page, simply visit the paths `/tags/` or `/categories/`. If you want the link to be displayed on the homepage, see `menu.toml`.

**Comment by iefnaf** [comment]
> 访问 `/tags/` 或者 `/categories/` 这两个路径即可打开对应汇总页面。如果想显示在主页上，配置 `menu.toml` 即可。
> 
> To open the corresponding page, simply visit the paths `/tags/` or `/categories/`. If you want the link to be displayed on the homepage, see `menu.toml`.

想问一下如何把categories页面下的多个项目展示到主页上呢？和展示posts一样的效果

**Comment by 9Marin** [comment]
Hello, is there any update on the subject ? 
Tried to setup a new entry showing categories with no success
`[[entries]]
title = "posts by category"

  [entries.categories_list]
  section = "categories"
  limit = 3
  show_more = true
  show_more_text = "See more posts..."
  show_more_url = "categories"`
