### ISSUE TITLE
support divide post list by year ?

### ISSUE THREAD

**Issue by ch3nnn** [hanwenguo/hugo-theme-nostyleplease#17]
example:

![image](https://github.com/g-hanwen/hugo-theme-nostyleplease/assets/40114564/163a8bf7-a38a-4499-839e-f15fc9ec8757)

**Comment by ch3nnn** [comment]
Resolved

**Comment by ch3nnn** [comment]
Can I commit RP ?  support switch post list by year

example: 
![image](https://github.com/g-hanwen/hugo-theme-nostyleplease/assets/40114564/2213cb7d-4988-4ab1-8a2f-a80612c7a0b5)

**Comment by g-hanwen** [comment]
Of course, PRs are welcomed. Thank you for your work!
